version: "3.5"
services:
  zero:
    image: debian:latest
    container_name: bank-dg0
    ports:
      - 6080:6080
    command: /gobin/dgraph zero --my=zero:5080 --replicas 3
    volumes:
      - type: bind
        source: $HOME/go/bin
        target: /gobin
        read_only: true
  dg1:
    image: debian:latest
    container_name: bank-dg1
    volumes:
      - type: bind
        source: $HOME/go/bin
        target: /gobin
        read_only: true
    ports:
      - 8180:8180
      - 9180:9180
    command: /gobin/dgraph server --my=dg1:7180 --lru_mb=2048 --zero=zero:5080 -o 100 --expose_trace --trace 1.0
  dg2:
    image: debian:latest
    container_name: bank-dg2
    volumes:
      - type: bind
        source: $HOME/go/bin
        target: /gobin
        read_only: true
    ports:
      - 8181:8181
      - 9181:9181
    command: /gobin/dgraph server --my=dg2:7181 --lru_mb=2048 --zero=zero:5080 -o 101 --expose_trace --trace 1.0
  dg3:
    image: debian:latest
    container_name: bank-dg3
    volumes:
      - type: bind
        source: $HOME/go/bin
        target: /gobin
        read_only: true
    ports:
      - 8182:8182
      - 9182:9182
    command: /gobin/dgraph server --my=dg3:7182 --lru_mb=2048 --zero=zero:5080 -o 102 --expose_trace --trace 1.0

